### ISSUE TITLE
图形展示问题

### ISSUE THREAD

**Issue by encodingl** [encodingl/skstack#51]
两条线展示的时候 数字小的反而在上方
![image](https://user-images.githubusercontent.com/16488016/87145473-f149e680-c2db-11ea-94c9-23adb0861aa6.png)

一条线展示数据正常
![image](https://user-images.githubusercontent.com/16488016/87145489-f73fc780-c2db-11ea-8ab6-a6f59a4b2266.png)

**Comment by devops-zeal** [comment]
已解决
